### ISSUE TITLE
Map pointer problem

### ISSUE THREAD

**Issue by EvalVis** [Boulderis/Locals-Trade#21]
Map pointer does not show when editing business (in edit branch). @MartynaUb could you fix that?

**Comment by MartynaUb** [comment]
Understood, will take care of it.

**Comment by EvalVis** [comment]
As I understood, it is resolved?

**Comment by MartynaUb** [comment]
Yes, it is fixed

**Comment by EvalVis** [comment]
Just marked your pull request. When you will merge it, this issue will close.
