### ISSUE TITLE
Dėl search engino

### ISSUE THREAD

**Issue by EvalVis** [Boulderis/Locals-Trade#3]
Pasimiršta search requestas, kai einama į kitą kategoriją arba į kitą verslo lentos puslapį.
Gal pasiūlytumėt sprendimą?

**Comment by Yar3k** [comment]
Manau taip ir turi būti. Jei renkiesi kažką kitą kaip kategoriją tai turi nusiresetinti search request

**Comment by EvalVis** [comment]
Navigation between pages is finally resolved in #17
