### ISSUE TITLE
Layout issues

### ISSUE THREAD

**Issue by EvalVis** [Boulderis/Locals-Trade#39]
For demonstration, two collection views in one content page were used, but they overlap. @Yar3k would you like to design Xamarin application?

**Comment by EvalVis** [comment]
So @Yar3k since time is of the essence, we should probably close this issue, we have some others more importants things to do, right?

**Comment by EvalVis** [comment]
But if you have time, please check individual business details page. Design in this page sucks.

**Comment by EvalVis** [comment]
I have fixed overlapping, but design is still poor.

**Comment by Yar3k** [comment]
Sorry. I cant run it now on my device. ☹

**Comment by EvalVis** [comment]
I do not think we will have time for.
